import type { NextPage } from 'next';
import Head from 'next/head';
import { useSelector } from 'react-redux';
import { useSignoutMutation } from '../modules/signout';
import { SignupForm, SigninForm } from '../modules/auth';
import { UserMetadataUpdateForm } from '../modules/user-metadata';
import { authUserSelector } from '../stores';

const Home: NextPage = () => {
  const { authUser } = useSelector(authUserSelector);
  const signoutMutation = useSignoutMutation();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {authUser && <h1>Hello {authUser.displayName}</h1>}
        <SignupForm />
        <SigninForm />
        <UserMetadataUpdateForm />
        <button onClick={() => signoutMutation.mutate(undefined)}>
          Signout
        </button>
      </main>
    </div>
  );
};

export default Home;
